-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Object.CategorizedObjectiveType exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.ScalarCodecs
import API.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int API.Object.CategorizedObjectiveType
id =
    Object.selectionForField "Int" "id" [] Decode.int


description : SelectionSet String API.Object.CategorizedObjectiveType
description =
    Object.selectionForField "String" "description" [] Decode.string


goalAreaIds : SelectionSet (List Int) API.Object.CategorizedObjectiveType
goalAreaIds =
    Object.selectionForField "(List Int)" "goalAreaIds" [] (Decode.int |> Decode.list)


tagIds : SelectionSet (List Int) API.Object.CategorizedObjectiveType
tagIds =
    Object.selectionForField "(List Int)" "tagIds" [] (Decode.int |> Decode.list)
